---
# tasks file for 2do_parcial

- debug:
    msg: "Tareas del 2do Parcial"
- name: "Crear directorios en /tmp/2doparcial/"
  file:
    path: "/tmp/2doparcial/{{ item }}"
    state: directory
    mode: '0775'
    recurse: yes
  with_items: 
    - "alumno"
    - "equipo"  
 


- name: "Agrego templates"
  template:
    src: template1.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
  template:
    src: template2.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt 

- name: "Agrego NOPASSWD en sudoers para el grupo 2PSupervisores"
  become: yes
  lineinfile:
    path: /etc/sudoers.d/desa
    state: present
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'   
